"""Generates firmware/common/test_vectors.json (PROTOCOL §9) with an implementation
independent from the C++ one (Python standard library: struct, hashlib, hmac).
The C++ native tests and the Pi daemon tests both consume the JSON file.

  python3 tools/gen_vectors.py
"""
import hashlib
import hmac
import json
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "test_vectors.json")

MAGIC, VERSION = 0x4E44, 1
T_DMX, T_CMD, T_ACK, T_HB, T_BEACON = 0x01, 0x10, 0x11, 0x20, 0x30
F_LAST, F_FRAG, F_AUTH = 1, 2, 4


def crc16(data, crc=0xFFFF):
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def packet(ptype, net_id, universe, seq, payload=b"", offset=0, flags=0, key=None, counter=None,
           version=VERSION, magic=MAGIC):
    flags = flags | (F_AUTH if key is not None else 0)
    hdr = struct.pack("<HBBHHHHHBB", magic, version, ptype, net_id, universe, seq, offset, len(payload), flags, 0)
    trailer = b""
    if key is not None:
        c = struct.pack("<I", counter)
        trailer = c + hmac.new(key, hdr + payload + c, hashlib.sha256).digest()[:8]
    crc = crc16(hdr + payload + trailer)
    return hdr + struct.pack("<H", crc) + payload + trailer


def cobs(data):
    """Canonical COBS: a 254-byte block that ends the input is not followed by 0x01."""
    out, block = bytearray(), bytearray()
    for i, b in enumerate(data):
        if b == 0:
            out += bytes([len(block) + 1]) + block
            block = bytearray()
        else:
            block.append(b)
            if len(block) == 254:
                out += bytes([255]) + block
                block = bytearray()
                if i == len(data) - 1:
                    return bytes(out)
    out += bytes([len(block) + 1]) + block
    return bytes(out)


def heartbeat_payload(hb):
    name = hb["name"].encode().ljust(16, b"\0")
    return (bytes.fromhex(hb["mac"]) + name + struct.pack("<H", hb["start_address"]) + bytes(hb["fw_version"])
            + struct.pack("<BBIbIIIIBBHBB", hb["variant"], hb["relay"], hb["relay_switch_count"], hb["rssi"],
                          hb["rx_frames"], hb["lost_frames"], hb["rejected_frames"], hb["uptime_s"], hb["status"],
                          hb["radio_channel"], hb["dmx_out_slots"], hb["reset_reason"], 0))


def tlv(items):
    return b"".join(bytes([k, len(v)]) + v for k, v in items)


def default_config_tlv(mac):
    """GET_CONFIG answer of a node with default settings (order = PROTOCOL table)."""
    m = bytes.fromhex(mac)
    name = ("node-%02X%02X%02X" % (m[3], m[4], m[5])).encode()
    u8, u16, u32 = (lambda v: bytes([v])), (lambda v: struct.pack("<H", v)), (lambda v: struct.pack("<I", v))
    return tlv([(0x01, u16(0)), (0x02, u16(1)), (0x03, name), (0x04, u8(6)), (0x05, u8(1)), (0x06, u8(2)),
                (0x07, u16(3000)), (0x08, u32(0)), (0x09, u8(0)), (0x0A, u8(22)), (0x0B, u16(500)),
                (0x0C, u16(4882)), (0x0D, u16(512)), (0x0E, u16(0)), (0x0F, u16(0)), (0x12, u8(1)),
                (0x13, u8(0))])


def main():
    net = 0x1234
    key = bytes(range(32))
    node_mac = "240ac4123456"
    v = {"comment": "Generated by firmware/common/tools/gen_vectors.py - do not edit",
         "crc": [{"ascii": "123456789", "crc": 0x29B1}, {"ascii": "", "crc": 0xFFFF},
                 {"hex": "4e44011034120000", "crc": crc16(bytes.fromhex("4e44011034120000"))}],
         "net_id": net, "net_key": key.hex(), "node_mac": node_mac}

    valid = []
    dmx8 = bytes([0, 1, 2, 3, 128, 255, 64, 32])
    valid.append({"name": "dmx_v2", "hex": packet(T_DMX, net, 3, 0x1001, dmx8, flags=F_LAST).hex(),
                  "my_net_id": net, "type": T_DMX, "universe": 3, "seq": 0x1001, "offset": 0,
                  "length": 8, "flags": F_LAST, "payload": dmx8.hex()})
    hb = {"mac": node_mac, "name": "lyre-cour", "start_address": 17, "fw_version": [1, 0, 2], "variant": 2,
          "relay": 5, "relay_switch_count": 1234, "rssi": -61, "rx_frames": 100000, "lost_frames": 42,
          "rejected_frames": 3, "uptime_s": 86400, "status": 0x11, "radio_channel": 6, "dmx_out_slots": 24,
          "reset_reason": 1}
    hbp = heartbeat_payload(hb)
    valid.append({"name": "heartbeat", "hex": packet(T_HB, net, 3, 77, hbp).hex(), "my_net_id": net,
                  "type": T_HB, "universe": 3, "seq": 77, "offset": 0, "length": len(hbp), "flags": 0,
                  "payload": hbp.hex(), "heartbeat": hb})
    bp = bytes([1, 0, 0, 2]) + struct.pack("<I", 3600)
    valid.append({"name": "beacon", "hex": packet(T_BEACON, net, 0xFFFF, 9, bp).hex(), "my_net_id": net,
                  "type": T_BEACON, "universe": 0xFFFF, "seq": 9, "offset": 0, "length": 8, "flags": 0,
                  "payload": bp.hex(), "beacon": {"fw_version": [1, 0, 0], "active_universes": 2, "uptime_s": 3600}})
    ident = bytes.fromhex("ffffffffffff") + bytes([0x01]) + struct.pack("<H", 10)
    valid.append({"name": "cmd_identify_broadcast", "hex": packet(T_CMD, net, 0xFFFF, 500, ident).hex(),
                  "my_net_id": net, "type": T_CMD, "universe": 0xFFFF, "seq": 500, "offset": 0,
                  "length": len(ident), "flags": 0, "payload": ident.hex(),
                  "command": {"target": "ffffffffffff", "opcode": 1, "args": struct.pack("<H", 10).hex()}})
    setc = tlv([(0x01, struct.pack("<H", 5)), (0x02, struct.pack("<H", 10)), (0x03, "lyre-1".encode())])
    cmd = bytes.fromhex(node_mac) + bytes([0x02]) + setc
    valid.append({"name": "cmd_set_config_unconfigured", "hex": packet(T_CMD, 0x0777, 0xFFFF, 501, cmd).hex(),
                  "my_net_id": 0, "type": T_CMD, "universe": 0xFFFF, "seq": 501, "offset": 0,
                  "length": len(cmd), "flags": 0, "payload": cmd.hex(),
                  "command": {"target": node_mac, "opcode": 2, "args": setc.hex()}})
    rel = bytes.fromhex(node_mac) + bytes([0x04, 1])
    valid.append({"name": "cmd_relay_auth", "hex": packet(T_CMD, net, 0xFFFF, 502, rel, key=key, counter=42).hex(),
                  "my_net_id": net, "type": T_CMD, "universe": 0xFFFF, "seq": 502, "offset": 0,
                  "length": len(rel), "flags": F_AUTH, "payload": rel.hex(), "auth_counter": 42,
                  "command": {"target": node_mac, "opcode": 4, "args": "01"}})
    ack = bytes([0x04, 0x00, 0x05])
    valid.append({"name": "ack_relay", "hex": packet(T_ACK, net, 0xFFFF, 502, ack).hex(), "my_net_id": net,
                  "type": T_ACK, "universe": 0xFFFF, "seq": 502, "offset": 0, "length": 3, "flags": 0,
                  "payload": ack.hex()})
    v["valid"] = valid

    # fragmented universe (v1 fallback): offsets 0 (232), 232 (232), 464 (48), seq 7
    uni = bytes((i * 7 + 3) & 0xFF for i in range(512))
    frags = []
    for off, ln in ((0, 232), (232, 232), (464, 48)):
        fl = F_FRAG | (F_LAST if off == 464 else 0)
        frags.append(packet(T_DMX, net, 3, 7, uni[off:off + ln], offset=off, flags=fl).hex())
    v["fragmented"] = {"seq": 7, "universe": 3, "frame": uni.hex(), "packets": frags}

    good = packet(T_DMX, net, 3, 1, dmx8, flags=F_LAST)
    bad_crc = bytearray(good)
    bad_crc[20] ^= 0xFF
    too_long = packet(T_DMX, net, 3, 1, bytes(20), offset=500, flags=F_FRAG | F_LAST)
    v["invalid"] = [
        {"name": "too_short", "hex": good[:17].hex(), "my_net_id": net, "reject": "too_short"},
        {"name": "bad_magic", "hex": packet(T_DMX, net, 3, 1, dmx8, flags=F_LAST, magic=0x4E45).hex(),
         "my_net_id": net, "reject": "magic"},
        {"name": "version_2", "hex": packet(T_DMX, net, 3, 1, dmx8, flags=F_LAST, version=2).hex(),
         "my_net_id": net, "reject": "version"},
        {"name": "foreign_net_id", "hex": packet(T_DMX, 0x9999, 3, 1, dmx8, flags=F_LAST).hex(),
         "my_net_id": net, "reject": "net_id"},
        {"name": "dmx_to_unconfigured", "hex": good.hex(), "my_net_id": 0, "reject": "net_id"},
        {"name": "length_mismatch", "hex": (good + b"\x00").hex(), "my_net_id": net, "reject": "length"},
        {"name": "bad_crc", "hex": bytes(bad_crc).hex(), "my_net_id": net, "reject": "crc"},
        {"name": "unknown_type", "hex": packet(0x55, net, 3, 1, dmx8).hex(), "my_net_id": net, "reject": "type"},
        {"name": "dmx_beyond_512", "hex": too_long.hex(), "my_net_id": net, "reject": "type_check"},
        {"name": "heartbeat_short", "hex": packet(T_HB, net, 3, 1, bytes(40)).hex(), "my_net_id": net,
         "reject": "type_check"},
    ]

    v["cobs"] = [{"raw": r.hex(), "enc": cobs(r).hex()} for r in (
        b"", b"\x00", b"\x00\x00", b"\x11\x22\x00\x33", b"\x11\x22\x33\x44", b"\x11\x00\x00\x00",
        bytes(range(1, 255)), bytes(range(1, 256)), bytes(range(0, 256)), bytes([1] * 600))]

    v["hmac_sha256"] = [
        {"key": b"Jefe".hex(), "data": b"what do ya want for nothing?".hex(),
         "mac": hmac.new(b"Jefe", b"what do ya want for nothing?", hashlib.sha256).hexdigest()},
        {"key": (b"\xaa" * 131).hex(), "data": b"Test Using Larger Than Block-Size Key - Hash Key First".hex(),
         "mac": hmac.new(b"\xaa" * 131, b"Test Using Larger Than Block-Size Key - Hash Key First",
                         hashlib.sha256).hexdigest()},
    ]
    v["sha256"] = [{"data": d.hex(), "hash": hashlib.sha256(d).hexdigest()}
                   for d in (b"", b"abc", b"a" * 1000)]
    v["config_default_tlv"] = {"mac": node_mac, "tlv": default_config_tlv(node_mac).hex()}

    with open(OUT, "w") as f:
        json.dump(v, f, indent=1)
    print("written", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
